name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check tag is on main
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})
          if ! git rev-list origin/main | grep -q "$TAG_COMMIT"; then
            echo "‚ùå Tag is not from main branch"
            exit 1
          fi

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

  build:
    needs: check
    env:
      CGO_ENABLED: "0"
      VERSION: ${{ github.ref_name }}
    strategy:
      matrix:
        include:
          - { goos: windows, goarch: amd64,           os: windows-latest }
          - { goos: windows, goarch: arm64,           os: windows-latest }
          - { goos: windows, goarch: "386",           os: windows-latest }
          - { goos: darwin,  goarch: arm64,           os: macos-latest }
          - { goos: darwin,  goarch: amd64,           os: macos-latest }
          - { goos: linux,   goarch: amd64,           os: ubuntu-latest }
          - { goos: linux,   goarch: arm64,           os: ubuntu-latest }
          - { goos: linux,   goarch: "386",           os: ubuntu-latest }
          - { goos: linux,   goarch: arm,   arm: "5", os: ubuntu-latest }
          - { goos: linux,   goarch: arm,   arm: "6", os: ubuntu-latest }
          - { goos: linux,   goarch: arm,   arm: "7", os: ubuntu-latest }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - if: ${{ matrix.goos != 'linux' }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make release
      - if: ${{ matrix.goos == 'linux' && matrix.goarch != 'arm' }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make release
      - if: ${{ matrix.goos == 'linux' && matrix.goarch == 'arm' }}
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.arm }} make release

      - uses: actions/upload-artifact@v6
        with:
          name: build-${{ matrix.goos }}_${{ matrix.goarch }}
          path: build/msr-downloader-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v7
        with:
          path: build
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          files: build/msr-downloader-*
          prerelease: ${{ contains(github.ref_name, '-rc') }}

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: build-*
